name: Build Core
on:
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: windows
            arch: x86_64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            lib_name: baad_core.dll
          - os: windows
            arch: aarch64
            runner: windows-latest
            target: aarch64-pc-windows-msvc
            lib_name: baad_core.dll
          - os: macos
            arch: x86_64
            runner: macos-15
            target: x86_64-apple-darwin
            lib_name: libbaad_core.dylib
          - os: macos
            arch: aarch64
            runner: macos-15
            target: aarch64-apple-darwin
            lib_name: libbaad_core.dylib
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            lib_name: libbaad_core.so
          - os: linux
            arch: aarch64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            lib_name: libbaad_core.so
    steps:
      - name: Clone source repository
        run: |
          git clone https://github.com/RZinth/BA-AD-Core.git source
          cd source

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('source/**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('source/**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: source/target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-build-target-${{ hashFiles('source/**/Cargo.lock') }}

      - name: Build
        working-directory: source
        run: cargo build --release --target ${{ matrix.target }} --features uniffi

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p ./publish/${{ matrix.target }}
          cp source/target/${{ matrix.target }}/release/${{ matrix.lib_name }} ./publish/${{ matrix.target }}/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: baad-core-${{ matrix.target }}
          path: publish/${{ matrix.target }}
